export const country = [
  { label: 'ae', value: 'United Arab Emirates' },
  { label: 'ar', value: 'Argentina' },
  { label: 'at', value: 'Austria' },
  { label: 'au', value: 'Australia' },
  { label: 'be', value: 'Belgium' },
  { label: 'bg', value: 'Bulgaria' },
  { label: 'br', value: 'Brazil' },
  { label: 'ca', value: 'Canada' },
  { label: 'ch', value: 'Switzerland' },
  { label: 'cn', value: 'China' },
  { label: 'co', value: 'Colombia' },
  { label: 'cu', value: 'Cuba' },
  { label: 'cz', value: 'Czech Republic' },
  { label: 'de', value: 'Germany' },
  { label: 'eg', value: 'Egypt' },
  { label: 'fr', value: 'France' },
  { label: 'gb', value: 'United Kingdom' },
  { label: 'gr', value: 'Greece' },
  { label: 'hk', value: 'Hong Kong' },
  { label: 'hu', value: 'Hungary' },
  { label: 'id', value: 'Indonesia' },
  { label: 'ie', value: 'Ireland' },
  { label: 'il', value: 'Israel' },
  { label: 'in', value: 'India' },
  { label: 'it', value: 'Italy' },
  { label: 'jp', value: 'Japan' },
  { label: 'kr', value: 'South Korea' },
  { label: 'lt', value: 'Lithuania' },
  { label: 'lv', value: 'Latvia' },
  { label: 'ma', value: 'Morocco' },
  { label: 'mx', value: 'Mexico' },
  { label: 'my', value: 'Malaysia' },
  { label: 'ng', value: 'Nigeria' },
  { label: 'nl', value: 'Netherlands' },
  { label: 'no', value: 'Norway' },
  { label: 'nz', value: 'New Zealand' },
  { label: 'ph', value: 'Philippines' },
  { label: 'pl', value: 'Poland' },
  { label: 'pt', value: 'Portugal' },
  { label: 'ro', value: 'Romania' },
  { label: 'rs', value: 'Serbia' },
  { label: 'ru', value: 'Russia' },
  { label: 'sa', value: 'Saudi Arabia' },
  { label: 'sg', value: 'Singapore' },
  { label: 'se', value: 'Sweden' },
  { label: 'si', value: 'Slovenia' },
  { label: 'sk', value: 'Slovakia' },
  { label: 'th', value: 'Thailand' },
  { label: 'tr', value: 'Turkey' },
  { label: 'tw', value: 'Taiwan' },
  { label: 'ua', value: 'Ukraine' },
  { label: 'us', value: 'United States' },
  { label: 've', value: 'Venezuela' },
  { label: 'za', value: 'South Africa' },
];

export const language = [
  { label: 'ar', value: 'Arabic' },
  { label: 'de', value: 'German' },
  { label: 'en', value: 'English' },
  { label: 'es', value: 'Spanish' },
  { label: 'fr', value: 'French' },
  { label: 'he', value: 'Hebrew' },
  { label: 'it', value: 'Italian' },
  { label: 'nl', value: 'Dutch' },
  { label: 'no', value: 'Norwegian' },
  { label: 'pt', value: 'Portuguese' },
  { label: 'ru', value: 'Russian' },
  { label: 'sv', value: 'Swedish' },
  { label: 'ud', value: 'Urdu' },
  { label: 'zh', value: 'Chinese' },
];
